# Generated by Django 6.0.4 on 2026-06-09 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='katagori',
            new_name='kategori',
        ),
        migrations.RenameField(
            model_name='buku',
            old_name='penagrang',
            new_name='pengarang',
        ),
        migrations.AlterField(
            model_name='buku',
            name='stok',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tgl_pinjam', models.DateField()),
                ('tgl_kembali', models.DateField()),
                ('status', models.CharField(default='Dipinjam', max_length=20)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjam.buku')),
            ],
        ),
    ]
