# Generated by Django 6.0.4 on 2026-05-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('umur', models.IntegerField()),
                ('tgl_lahir', models.DateField()),
                ('nilai_akhir', models.IntegerField(default=0)),
            ],
        ),
    ]
